global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'raspberry_pi_telegraf'
    static_configs:
      - targets: ['192.168.1.127:9273']
        labels:
          location: 'home'
          device: 'raspberry_pi_zero'
          type: 'system'

  - job_name: 'mymachine'
    static_configs:
      - targets: ['localhost:9090']